export enum OrderLineType {
  PHYSICALITEM = 'PHYSICALITEM',

  DIGITALITEM = 'DIGITALITEM',

  SHIPPINGCOST = 'SHIPPINGCOST',

  PAYMENTCOST = 'PAYMENTCOST',

  DISCOUNT = 'DISCOUNT',

  GIFTCARD = 'GIFTCARD',

  SHOPCREDIT = 'SHOPCREDIT',
}
