export enum PaymentStepAction {
  DISPLAYHOSTEDPAGE = 'DISPLAYHOSTEDPAGE',

  PAYMENTMETHODSELECTION = 'PAYMENTMETHODSELECTION',

  START = 'START',

  PROCESS = 'PROCESS',

  BACKGROUNDPROCESS = 'BACKGROUNDPROCESS',

  CAPTURE = 'CAPTURE',

  REFUND = 'REFUND',

  CANCEL = 'CANCEL',
}
